# Generated by Django 5.0.7 on 2024-09-01 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='image',
            new_name='imagem',
        ),
    ]
