# Generated by Django 5.0.7 on 2024-09-04 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_categoria_options_remove_foto_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
    ]
