# Generated by Django 5.0.7 on 2024-09-01 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_image_foto_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='imagem',
            new_name='image',
        ),
    ]
