# Generated by Django 5.0.7 on 2024-09-03 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_imagem_foto_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='foto',
            options={'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos'},
        ),
    ]
