# Generated by Django 5.0.7 on 2024-09-05 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_categoria_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='foto',
            options={},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='categoria',
        ),
    ]
