# Generated by Django 5.0.7 on 2024-09-05 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_categoria_options_alter_foto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.categoria'),
            preserve_default=False,
        ),
    ]
