# Generated by Django 5.0.7 on 2024-09-05 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_foto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='base.categoria'),
        ),
    ]
