name: Fly Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group  # Garante que apenas uma execução ocorra por vez

    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@v1  # Usa versão estável da ação Fly.io

      - name: Verifying FLY_API_TOKEN
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          if [ -z "$FLY_API_TOKEN" ]; then
            echo "FLY_API_TOKEN is not set!"
            exit 1
          else
            echo "Token length: ${#FLY_API_TOKEN}"
          fi
          
      - name: Deploying to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
